In [1]:
import pandas as pd
import numpy as np

#Import Data
data = pd.read_csv('SampleData.csv')

# Create Pivot
AST = pd.pivot_table(data, 
                    values=['MTD', '3M', '6M', 'YTD'], 
                    index=['strategy_classification'], 
                    aggfunc=np.mean
                    )

#Sort Alphabetically by strategy_classification
AST['labels'] = AST.index.str.lower()
AST = AST.sort_values('labels').drop('labels', axis=1)

# If you wanted to add in a new column with a numeric index then you would not drop the column above, and include this:
#AST.index = [i for i in range(len(AST.index))]

#Re-order Columns
AST = AST[['MTD', '3M', '6M', 'YTD']]

#Convert numbers into percentage
AST['MTD'] = pd.Series(["{0:.2f}%".format(val * 100) for val in AST['MTD']], index = AST.index)
AST['3M'] = pd.Series(["{0:.2f}%".format(val * 100) for val in AST['3M']], index = AST.index)
AST['6M'] = pd.Series(["{0:.2f}%".format(val * 100) for val in AST['6M']], index = AST.index)
AST['YTD'] = pd.Series(["{0:.2f}%".format(val * 100) for val in AST['YTD']], index = AST.index)

AST

                            MTD      3M      6M     YTD
strategy_classification
Commodity                 0.29%   0.76%  -2.17%   1.01%
CTA                       0.24%  -0.52%   0.01%  -1.80%
Equity Market Neutral     0.15%  -0.45%   0.08%  -0.81%
Fixed Income              0.81%  -0.02%  -0.07%   2.39%
Quant Macro               0.40%  -0.40%   0.33%  -1.04%
Volatility               -0.12%   0.51%  -2.81%  -0.88%